---
################################################### Пьеса для БД ###########################################################
############################################################################################################################

- name: Configure MongoDB
  hosts: db
  become: true

  roles:
    - db

