---
################################################### Пьеса для деплоя #######################################################
############################################################################################################################


- name: Deploy app
  hosts: app
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        #update_cache: yes

    - name: Fetch the latest version of application code
      git: #ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

