---
################################################### Пьеса для БД ###########################################################
############################################################################################################################

- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongodb config file
      template:
        src: templates/mongodb.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      notify: restart mongodb

  handlers:
    - name: restart mongodb
      service: name=mongodb state=restarted


################################################### Пьеса для приложения ###################################################
############################################################################################################################

- name: Configure app
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.0.0.9
  tasks:
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      service: name=puma state=restarted


################################################### Пьеса для деплоя #######################################################
############################################################################################################################

- name: Deploy app
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        #update_cache: yes

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
    - name: reload puma
      service: name=puma state=restarted

