---
- name: Configure hosts & deploy application  # <-- Словесное описание сценария (name)
  hosts: all  # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  vars: # <-- Блок с переменными 
    mongo_bind_ip: 0.0.0.0  # <-- Переменная для шаблона задается в блоке vars
    db_host: 10.0.0.29 # <-- внутренний IP инстанса db
  tasks:  # <-- Блок тасков (заданий), которые будут выполняться для данных хостов
    - name: Change mongodb config file # <-- Имя задания (таски)
      become: true  # <-- Выполнить задание от root
      template: # <-- Имя применяемого модуля - template
        src: templates/mongodb.conf.j2  # <-- Путь до локального файла-шаблона
        dest: /etc/mongodb.conf  # <-- Путь на удаленном хосте
        mode: 0644  # <-- Права на файл, которые нужно установить
      tags: db-tag # <-- Список тэгов для задачи
      notify: restart mongodb # <-- Вызов handler'а  
    
    - name: Install git
      become: true
      apt:
        name: git
        state: present
        #update_cache: yes
      tags: app-tag

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag 

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith  # <-- Указываем нужную ветку
      tags: app-tag #deploy-tag-reddit
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit  # <-- В какой директории выполнить команду bundle
      tags: app-tag #deploy-tag

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

  handlers:  # <-- Добавим блок handlers и задачи
    - name: restart mongodb # <-- !!!ВНИМАНИЕ!!! сервис называется mongodb, а не mongod
      become: true
      service: name=mongodb state=restarted
    - name: reload puma # <-- Данный handler укажет systemd, что unit для сервиса изменился и его следует перечитать
      become: true
      service: name=puma state=restarted

